### PR TITLE
Basic GPU Support

### PR DESCRIPTION
**Pull request by nic-barbara**
Adding basic GPU support in accordance with https://github.com/acfr/RobustNeuralNetworks.jl/issues/105.

### CODE REVIEW

**Comment by nic-barbara** [comment]
Main thing to change is removing scalar indexing when constructing parameterisations. Scalar indexing is not done on the GPU which can lead to very expensive data transfer back and forth between CPU and GPU.

**Comment by nic-barbara** [comment]
This seemed like a good time to change the `LBDN` back-end a little bit. The number of hidden layers `nh` is now stored as an `NTuple` rather than a `Vector`. This means it's immutable, and won't get loaded onto the GPU when we don't actually want it to. I've still left the option of specifying `nh` with a vector in the constructor though, both for backwards compatibility and ease of use.

**Comment by nic-barbara** [comment]
There was a rather frustrating bug when evaluating the RENs on a GPU. In the `src/Base/acyclic_ren_solver.jl`, we used `similar(z_eq, 1, size(b,2))` to initialise the product term `Di_zi`. On the CPU, `similar()` always initialises the array with extremely small values that are effectively zero. This is not the case on the GPU. On the GPU, `similar()` can initialise the arrays with basically anything, including `NaN`.

This was causing the REN to have different outputs when evaluated multiple times with the same inputs. Sometimes, the outputs would be `NaN`. Constructing `Di_zi = typeof(b)(zeros(Float32, 1, size(b,2)))` seems to work much better.

**Review by raywang1987 — APPROVED** [review]

**Review by jclinton830 — APPROVED** [review]
Looks good!

**Pull request merged**
